# Importing Numpy, Numpy Array Creation  **🇦**

In [2]:
import numpy as np
print("Numpy Version: ", np.__version__)

arr = np.array([1, 2, 3, 4, 5])
print(arr)


Numpy Version:  2.0.2
[1 2 3 4 5]


In [5]:
print("Type of Array: ", type(arr))
print("Dimension of Array arr is: ", arr.ndim)

d0 = np.array(23)
print("Dimension of Array d0 is :", d0.ndim)
fruit_list = ["apple", "banana", "cherry"]
print(fruit_list)

print("Type of fruit_list is :", type(fruit_list))
fruit_list = np.array(fruit_list)
print("Type of fruit_list is :", type(fruit_list))


Type of Array:  <class 'numpy.ndarray'>
Dimension of Array arr is:  1
Dimension of Array d0 is : 0
['apple', 'banana', 'cherry']
Type of fruit_list is : <class 'list'>
Type of fruit_list is : <class 'numpy.ndarray'>


# Basic Array Operation **🔀**

*1D, 2D, 3D*

In [12]:
import numpy as no

a1 = no.array([1, 2, 3, 4, 5])
print("1D Array :", a1)
print("Dimension of Array a1 is :", a1.ndim)

a2 = no.array( [ [1, 2, 3], [4, 5, 6] ] )
print("2D Array :", a2)
print("Dimension of Array a is :", a2.ndim)

print("Element at (1,0) row 1 column 0 of 2D Array is :", a2[1,0])

a3 = no.array([[[1,2,3], [4,5,6], [1,2,3]]])
print("3D Array :", a3)
print("Dimension of Array a is :", a3.ndim)

a4 = no.array([[[[1,2,3], [4,5,6]],[[7,8,9], [0,1,2]]]])
print("4D Array :", a4)
print("Dimension of Array a is :", a4.ndim)

a5 = no.array([1, 2, 3, 4], ndmin=5)
print("5D Array :", a5)
print("Dimension of Array a is :", a5.ndim)



1D Array : [1 2 3 4 5]
Dimension of Array a1 is : 1
2D Array : [[1 2 3]
 [4 5 6]]
Dimension of Array a is : 2
3D Array : [[[1 2 3]
  [4 5 6]
  [1 2 3]]]
Dimension of Array a is : 3
4D Array : [[[[1 2 3]
   [4 5 6]]

  [[7 8 9]
   [0 1 2]]]]
Dimension of Array a is : 4
5D Array : [[[[[1 2 3 4]]]]]
Dimension of Array a is : 5
Element at (1,0) row 1 column 0 of 2D Array is : 4


In [13]:
import numpy as nm
d3array = nm.array([
    [ # Depth 0
      [1,2,3], # Row 0
      [4,5,6]  # Row 1
    ],
    [ # Depth 1
      [7,8,9], # Row 0
      [0,1,2]  # Row 1
    ],
    [ # Depth 2
      [3,2,1], # Row 0
      [1,2,3]  # Row 1
    ]
])
print("Dimension of Array a is :", d3array.ndim)
print(d3array)

item = d3array[0, 1, 2] # Depth 2, Row 0, Column 0
print("Item at d3array[2][0][0] is :", d3array[2][0][0])


Dimension of Array a is : 3
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]

 [[3 2 1]
  [1 2 3]]]
Item at d3array[2][0][0] is : 3


## Numpy Array Slicing 🥭

In [19]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7])
print("Element of Array d1 are : ", d1)
print("Element of Array d1 from 1 to 5 are : ", d1[1:5])
print("Element of Array d1 from 4 to end are : ", d1[4:])
print("Element of Array d1 from start to 4 are : ", d1[:4])
print("Element of Array d1 from start to end are : ", d1[:])
print("Element of Array d1 from start to end with step 2 are : ", d1[::2])
print("Element of Array d1 from start to end with step 3 are : ", d1[::3])

d2 = np.array([[3,4,5,7], [6,7,8,9], [3,5,7,9]])
print("Element of Array d2 are: ", d2)
print("Element of Array d2 from 1 to 3 are: ", d2[0,1:3])
print("Element of Array d2 from 1 to 3 are: ", d2[1,1:3])
print("Element of Array d2 from 1 to 3 are: ", d2[2,1:3])
print("Element of Array d2 from 1 to 3 are: ", d2[:,1:3])
print("Array d2 slicing with step:d1[1:6:2]", d2[1:6:2])


Element of Array d1 are :  [1 2 3 4 5 6 7]
Element of Array d1 from 1 to 5 are :  [2 3 4 5]
Element of Array d1 from 4 to end are :  [5 6 7]
Element of Array d1 from start to 4 are :  [1 2 3 4]
Element of Array d1 from start to end are :  [1 2 3 4 5 6 7]
Element of Array d1 from start to end with step 2 are :  [1 3 5 7]
Element of Array d1 from start to end with step 3 are :  [1 4 7]
Element of Array d2 are:  [[3 4 5 7]
 [6 7 8 9]
 [3 5 7 9]]
Element of Array d2 from 1 to 3 are:  [4 5]
Element of Array d2 from 1 to 3 are:  [7 8]
Element of Array d2 from 1 to 3 are:  [5 7]
Element of Array d2 from 1 to 3 are:  [[4 5]
 [7 8]
 [5 7]]
Array d2 slicing with step:d1[1:6:2] [[6 7 8 9]]


## Numpy Data Types **📁**

In [21]:
import numpy as np

# integer
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype)

# boolean
arr = np.array([True, False, True])
print(arr)
print(arr.dtype)

# unsigned integer
arr1 = np.array([1, 2, 3, 4], dtype='uint8')
print(arr1)
print(arr1.dtype)

# float
arr2 = np.array([1.1, 2.1, 3.1])
print(arr2)
print(arr2.dtype)

# complex float
arr3 = np.array([1.1+1j, 2.2+1j])
print(arr3)
print(arr3.dtype)

# timedelta
arr4 = np.timedelta64(1, 'D')
print(arr4)
print(arr4.dtype)

# datetime
arr5 = np.array(['2020-02-13', '2021-01-23'])
print(arr5)
print(arr5.dtype)

# object
arr6 = np.array(["apple", "banana", "cherry"])
print(arr6)
print(arr6.dtype)

# string
arr7 = np.array(["apple", "banana", "cherry"], dtype='S')
print(arr7)
print(arr7.dtype)

# unicode string
arr8 = np.array([u'\x41', u'\x42'])
print(arr8)
print(arr8.dtype)

# void
arr9 = np.array([], dtype='V')
print(arr9)
print(arr9.dtype)


[1 2 3 4]
int64
[ True False  True]
bool
[1 2 3 4]
uint8
[1.1 2.1 3.1]
float64
[1.1+1.j 2.2+1.j]
complex128
1 days
timedelta64[D]
['2020-02-13' '2021-01-23']
<U10
['apple' 'banana' 'cherry']
<U6
[b'apple' b'banana' b'cherry']
|S6
['A' 'B']
<U1
[]
|V8


### Numpy Array Reshape **🥘**

In [24]:
c2 = np.array([[11,22,33,43], [43,54,67,65]])
c2shape =c2.shape # Get the shape of the array

print("Shape of the Array: ", c2shape)
print("Dimension of the Array: ", c2.ndim)

a2D = np.array([[1,2], [3,4]])
print("Array a2D: ", a2D)
a2D.reshape(-1) # array flatten through reshape

Shape of the Array:  (2, 4)
Dimension of the Array:  2
Array a2D:  [[1 2]
 [3 4]]


array([1, 2, 3, 4])

## Numpy Array Copy vs View **©**

In [ ]:
d = np.array ([1,2,3,4,5,6])
print("Array d is: ", d)

# copy
e = d[:2]
print("Array e is: ", e)


## Numpy Array Iteration **➰**

In [29]:
c1 = np.array([5,6,7,8,9,43,21,1])
for x in c1:
  print(x)

c2 = np.array([[11,22,33,43], [43,54,67,65]])
for x in c2:
  for i in x:
    print(i)

c3 = np.array([
    [[1,2,3],[3,5,7]],[[6,5,3],[11,13,12]],
    [[11,54,63], [12,52,76]]])
for x in c3:
  for i in x:
    for j in i:
      print(j)
print("Dimension of array is: ", c3.ndim)

5
6
7
8
9
43
21
1
11
22
33
43
43
54
67
65
1
2
3
3
5
7
6
5
3
11
13
12
11
54
63
12
52
76
Dimension of array is:  3


## Other Operation on Numpy **🫀**

In [32]:
# joining
e1 = np.array([1,2,3,4,5])
e2 = np.array([6,7,8,9,10])
e3 = np.concatenate([e1,e2])
print(e3)

# Splitting
e4 = np.array([1,2,3,4,5,6])
e5 = np.array_split(e4,3)
print(e5)

# Searching
e6 = np.array([1,2,3,4,56,7])
x = np.where(e6 == 4)
print("Search index of 4: ", x)

# Sorting
e7 = np.array([3,4,5,7,3,2,8,0,1])
y = np.searchsorted(e7, 8)
print("Index of 8 is :", y)


[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2]), array([3, 4]), array([5, 6])]
Search index of 4:  (array([3]),)
Index of 8 is : 9


# Task 3x3 matrix **🍱**

In [33]:
import numpy as np

# Step 1: Create a flat array 2 to 10
array_1d = np.arange(2, 11)

# Step 2: Reshape to 3x3 matrix
matrix = array_1d.reshape(3, 3)

# Step 3: Convert to float type
matrix_float = matrix.astype(float)

# Step 4: Flatten the matrix back to 1D
flat_array = matrix_float.flatten()

# Step 5: Find max and min
max_val = np.max(flat_array)
min_val = np.min(flat_array)

print("Matrix:")
print(matrix_float)
print("Maximum:", max_val)
print("Minimum:", min_val)


Matrix:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Maximum: 10.0
Minimum: 2.0
